---
# tasks file for roles/newuser

- stat:
    path: "/home/{{ variable_user }}"
  register: result

- debug:
    msg: "{{ variable_user }} home directory exists already.  Will not create user."
  when: result.stat.exists == true and result.stat.isdir == true

- debug:
    msg: "{{ variable_user }} home directory doesn't exist.  Will create user."
  when: result.stat.exists == false

- name: "Create a login user - {{ variable_user }}" # See this item for further info https://stackoverflow.com/questions/19292899/creating-a-new-user-and-password-with-ansible
  user:
    name: "{{ variable_user }}"
    uid: "{{ variable_uid }}"
    # password: "{{ my_password }}"
    state: present
    shell: /bin/bash # Defaults to /bin/bash
    system: no # Defaults to no
    createhome: yes # Defaults to yes
  when: result.stat.exists == false

- name: "Set login user password - {{ variable_user }}"
  user:
    name: "{{ variable_user }}"
    password: "{{ my_password }}"
  when: ( my_password ) and ( my_password | length > 0 )
  become: true

- name: Ensure primary group for user exists
  group:
    name: "{{ variable_user }}"
    state: present
    gid: "{{ variable_user_gid }}"

- name: 'adding existing user {{ variable_user }} to group wheel'
  user:
    name: "{{ variable_user }}"
    groups: wheel
    append: yes
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' ) and ( sudo | bool )

- name: 'adding existing user {{ variable_user }} to group sudo'
  user:
    name: "{{ variable_user }}"
    groups: sudo
    append: yes
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ( sudo | bool )

- name: "Allow {{ variable_user }} group to have passwordless sudo"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ variable_user }}"
    line: "%{{ variable_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  when: ( sudo | bool ) and ( passwordless_sudo | bool )
