repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/firehawkvfx/pre-commit
    rev: v0.0.2_firehawk
    hooks:
      - id: packer-validate
      # - id: shellcheck
