#cloud-config

# packages:
# - apt-transport-https
# - ca-certificates
# - curl
# - gnupg-agent
# - software-properties-common

# # Enable ipv4 forwarding, required on CIS hardened machines
# write_files:
# - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
#     content: |
#     net.ipv4.conf.all.forwarding=1

# # create the docker group
# groups:
# - docker

# # Add default auto created user to docker group
# system_info:
# default_user:
#     groups: [docker]

runcmd:
# Log found at /var/log/cloud-init-output.log
- echo "User data script started"
- sudo sed -i '/# End of file/i * soft nofile unlimited' /etc/security/limits.conf
- sudo sed -i '/# End of file/i * hard nofile unlimited' /etc/security/limits.conf
- sudo sed -i '/# End of file/i * soft nproc unlimited' /etc/security/limits.conf
- sudo sed -i '/# End of file/i * hard nproc unlimited' /etc/security/limits.conf
- echo "DONE SETTING UP STACK SIZE"