#cloud-config

runcmd:
- echo "User data script started"
- sudo sed -i '/# End of file/i * soft nofile unlimited' /etc/security/limits.conf
- sudo sed -i '/# End of file/i * hard nofile unlimited' /etc/security/limits.conf
- sudo sed -i '/# End of file/i * soft nproc unlimited' /etc/security/limits.conf
- sudo sed -i '/# End of file/i * hard nproc unlimited' /etc/security/limits.conf
- echo "DONE SETTING UP STACK SIZE"