---

- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_connect_as_user | default(ansible_user) }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  tasks:
  - name: Init ansible to get collections
    debug:
      msg: "Init ansible to get collections"
